version: '3.9'

services:
  app:
    build:
      context: .
    image: ticket-booking
    container_name: ticket-booking
    tty: true
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - application
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/src/app
    command: air -c .air.toml

  db:
    image: postgres:15-alpine
    container_name: ticket-booking-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  application:

volumes:
  postgres-db:
